### ISSUE TITLE
Create PR template for model contribution

### ISSUE THREAD

**Issue by sunya-ch** [sustainable-computing-io/kepler-model-db#5]
We need a PR template for contributor to fill in when uploading a new trained pipeline to the model DB.

Information we need for review
- [ ] kepler-model-server version
- [ ] training pipeline information (if not equal to std_v<version>)
   - [ ] extractor, isolator, trainers
   - [ ] bechmarks

Checklist
- [ ] has machine information in models/README.md and has link to CPU model if provided
- [ ] pipeline folder contains 
  - [ ] pipeline metadata (metadata.json)
  - [ ] train arguments (train_arguments.json)
  - [ ] model metadata summary files (xxx_model_metadata.csv)
  - [ ] visualized preprocess data in preprocessed_data
  - [ ] all models listed in model metadata summary files in the structure <energy source>/<output type>/<feature group>
- [ ] has training information in models/<version>/README.md and matches the value in pipeline metadata
- [ ] has pipeline description if not equal to std_v<version>
- [ ] has train arguments matches pipeline description
- [ ] verified account matches publisher in pipeline metadata

TODO:
- separate pipeline description to another folder
- add pipeline column in models/<version>/README.md#trained-pipelines with link to pipeline description
- add publisher column in  models/<version>/README.md#trained-pipelines with link to GitHub account page

Examples:
https://github.com/sustainable-computing-io/kepler-model-db/blob/main/models/README.md
https://github.com/sustainable-computing-io/kepler-model-db/blob/main/models/v0.6/README.md

**Comment by sunya-ch** [comment]
@mcalman https://github.com/sustainable-computing-io/kepler-model-db/pull/11 doesn't work. Could you try renaming the file to `pull_request_template.md` and move it under .github folder.
Check this https://github.com/appsmithorg/appsmith/issues/826#issuecomment-703093426.

**Comment by mcalman** [comment]
A customized link (e.g. https://github.com/sustainable-computing-io/kepler-model-db/compare/main...mcalman:test-1?template=add_pipeline_template.md) does work for me, but of course having the user manually alter the URL is not an elegant solution. The bug with GitHub seems to be that if you use a generic link (e.g. https://github.com/sustainable-computing-io/kepler-model-db/compare/main...?template=add_pipeline_template.md) the query parameter is lost in the process of selecting the branch you'd like to compare.

> Could you try renaming the file to `pull_request_template.md` and move it under .github folder.

I believe this would work to populate it, but then all PR's (including bug fixes and enhancements) would be populated with this template and not just new model contributions.

What do you think about this as a solution: https://stackoverflow.com/a/75030350?

**Comment by sunya-ch** [comment]
> A customized link (e.g. https://github.com/sustainable-computing-io/kepler-model-db/compare/main...mcalman:test-1?template=add_pipeline_template.md) does work for me, but of course having the user manually alter the URL is not an elegant solution. The bug with GitHub seems to be that if you use a generic link (e.g. https://github.com/sustainable-computing-io/kepler-model-db/compare/main...?template=add_pipeline_template.md) the query parameter is lost in the process of selecting the branch you'd like to compare.
> 
> > Could you try renaming the file to `pull_request_template.md` and move it under .github folder.
> 
> I believe this would work to populate it, but then all PR's (including bug fixes and enhancements) would be populated with this template and not just new model contributions.
> 
> What do you think about this as a solution: https://stackoverflow.com/a/75030350?

Thank you @mcalman 
Sure, the solution to put the expand link in the main template looks good to me. Please proceed the PR.
Also, may add instruction like if the PR doesn't match any category just put the content below.

**Comment by sunya-ch** [comment]
Closed by https://github.com/sustainable-computing-io/kepler-model-db/pull/13 merged
